yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path(r'^admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path(r'^auth/', include('users.urls', namespace='users')),
    path(r'^auth/', include('django.contrib.auth.urls')),
    path(r'^about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

TEXT_LIMIT_POST: int = 15
TEXT_LIMIT_COMMENT: int = 30

User = get_user_model()


class Group(models.Model):
    title = models.fields.CharField(
        max_length=200,
        verbose_name='Заголовок'
    )
    slug = models.fields.SlugField(
        max_length=255,
        unique=True,
        verbose_name='Заголовок'
    )
    description = models.fields.TextField(
        max_length=255,
        verbose_name='Описание'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст публикации'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор публикации'
    )

    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой относится публикация'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Загрузите сюда вашу картинку'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:TEXT_LIMIT_POST]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Комментарии'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор публикации'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Напишите комментарий',
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True,
    )

    def __str__(self):
        return self.text[:TEXT_LIMIT_COMMENT]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'], name='follow')
        ]

yatube/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)
        labels = {
            'text': _('Тело сообщения'),
            'group': _('Группа сообщения'),
            'image': _('Картинка к сообщению'),
        }
        help_texts = {
            'text': _('Введите сообщение'),
            'group': _('Укажите группу сообщения'),
            'image': _('Добавьте картинку'),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': _('Текст комментария'),
        }

yatube/posts/views.py
""" YaTube Social Community
Copyright (C) 2022 Authors: Dmitry Korepanov, Yandex practikum
License Free
Version: 1.0.6. 2022"""


from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie

from . import helpers
from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

QUANTITY_RECORDS: int = 10
POST_TITLE_CHAR: int = 30


@cache_page(20)
@vary_on_cookie
def index(request):
    paginator = Paginator(
        Post.objects.all(), QUANTITY_RECORDS
    )
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_list(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = helpers.pagination(posts, request, QUANTITY_RECORDS)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    user = request.user
    following = user.is_authenticated and author.following.exists()
    posts = author.posts.all()
    page_obj = helpers.pagination(posts, request, QUANTITY_RECORDS)
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    post_title = post.text[:POST_TITLE_CHAR]
    author = post.author
    number_author_posts = author.posts.all().count()
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'post_title': post_title,
        'author': author,
        'post_id': post_id,
        'number_author_posts': number_author_posts,
        'pub_date': post.pub_date,
        'comments': comments,
        'form': form
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
    )
    if form.is_valid():
        temp_form = form.save(commit=False)
        temp_form.author = request.user
        temp_form.save()
        return redirect(
            'posts:profile', temp_form.author
        )
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, pk=post_id)
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, QUANTITY_RECORDS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    follow_author = get_object_or_404(User, username=username)
    if follow_author != request.user:
        follow_author = Follow.objects.get_or_create(
            user=request.user,
            author=follow_author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    follow_author = get_object_or_404(User, username=username)
    data_follow = request.user.follower.filter(author=follow_author)
    if data_follow.exists():
        data_follow.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
  Сохранить запись
{% else %}
  Добавить запись
{% endif %}  
{% endblock %}
{% load user_filters %}
{% block content %} 
{% load thumbnail %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                Редактировать пост
                {% else %}
                Новый пост
                {% endif %}
              </div>
              <div class="card-body">
              {% if is_edit %}
                <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.pk %}">
              {% else %}
                <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
              {% endif %}
                {% csrf_token %}
                {% for field in form %}
                 <div class="form-group row my-3 p-3 textarea">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>    
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                 </div>
                 {% endfor %}
                 <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                 </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}
{% include 'includes/footer.html' %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Публикации избранных авторов
{% endblock %} 
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% load thumbnail %}
  {% for post in page_obj %}
  <div class="container col-lg-9 col-sm-12">
    <ul>
    <li>
      <b>Автор:</b>
      <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if post.group %}
    <li>
      <p><b>Группа:</b> 
      <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a></p>
    </li>
    {% endif %}
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaks }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">(подробная информация)</a>    
    {% if not forloop.last %}<hr>{% endif %}
  </div>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %} 
{% block content %}
{% load thumbnail %}
<div class="container col-9">
  <h2>{{ group.title }}</h2>
  <h3>{{ group.description|linebreaks }}</h3>
</div>
<br>
{% for post in page_obj %}
<div class="container col-lg-9 col-sm-12">
  <article>
  <ul>
	  {% if post.author %}
      <li>
        <b>Автор:</b>
        <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
      </li>
	  {% endif %}
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaks }}</p> 
  <a href="{% url 'posts:post_detail' post.pk %}">(подробная информация)</a>
  </article>
</div>
{% endfor %}
{% include 'posts/includes/paginator.html' %}   
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %} 
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% load thumbnail %}
  {% for post in page_obj %}
<div class="container col-lg-9 col-sm-12">
  <article>
    <ul>
	  {% if post.author %}
      <li>
        <b>Автор:</b>
        <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
      </li>
	  {% endif %}
      <li>
        <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    <p>
      {{ post.text|linebreaks }}
    </p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a> <br>
    {% if post.group %}
    <li>
      <b>Группа:</b>
      <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a></p>
    </li>
    {% endif %}
  </article>
    {% if not forloop.last %}<hr>{% endif %}
 </div>
{% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
<div class="container col-lg-9 col-sm-12">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
            </b>Дата публикации:</b><br> {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}   
            <li class="list-group-item">
            <b>Группа:</b> <a href="{% url 'posts:group_list' post.group.slug %}">
                {{ post.group.title }}</a>
            </li>
            {% endif %}
            <li class="list-group-item">
            <b>Автор:</b> <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            <b>Всего постов автора:</b> {{ number_author_posts }}
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-8">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
             <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
		</article>
          {% if post.author == user %}
          <a href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>;
          {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h6 class="card-header">Добавить комментарий:</h6>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.get_full_name }}
              </a>
            </h5>
              <p>
              {{ comment.text }}
              </p>
          </div>
        </div>
      {% endfor %}
      </div> 
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="mb-5">
  <h2>Все посты пользователя {{ author.get_full_name }} </h2>
  <h3>Всего постов: {{ author.posts.count }}</h3>
    {% if user != author %}
      {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button">
        Отписаться
      </a>
      {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button">
        Подписаться
      </a>
      {% endif %}
    {% endif %}
   <br>
 </div>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>Автор: {{ author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
      {% if post.group %}
      <li>
        <p>
          Группа:
          <a href="{% url 'posts:group_list' post.group.slug %}">
		    {{ post.group.title }}</a>
        </p>
      </li>
      {% endif %}
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text|linebreaks }}
      <a href="{% url 'posts:post_detail' post.pk %}">(подробная инфомация)</a>
    </p>
  </article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}